# 4.5 读取和存储

In [2]:
import torch
from torch import nn

print(torch.__version__)

1.9.0


## 4.5.1 读写`Tensor`

In [2]:
x = torch.ones(3)
torch.save(x, 'x.pt')

In [3]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [5]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

## 4.5.2 读写模型
### 4.5.2.1 `state_dict`

In [11]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.1276, -0.0361,  0.2162],
                      [ 0.1115, -0.4488,  0.2391]])),
             ('hidden.bias', tensor([0.3646, 0.5062])),
             ('output.weight', tensor([[ 0.1122, -0.6856]])),
             ('output.bias', tensor([-0.6644]))])

In [12]:
# net.named_parameters
# for param in net.parameters():
#     print(param)

In [13]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [0, 1, 2, 3]}]}

### 4.5.2.2 保存和加载模型

In [14]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])